### ISSUE TITLE
Prompt user to save unsaved changes

### ISSUE THREAD

**Issue by Welding-Torch** [szktkfm/mdtt#9]
If a user adds content to a table then quits- the user should be prompted to save unsaved changes to a file.
![image](https://github.com/szktkfm/mdtt/assets/46340124/048639c2-f396-4cd0-96c0-3955af0428b6)
In the above image, changes to the table are not saved to file after editing.

**Comment by szktkfm** [comment]
`mdtt` provides the `-i` option for modifying files, which enables "in-place" editing similar to sed. Indeed, typical editors often alert users to unsaved changes if they attempt to quit without saving. However, if `mdtt` were to offer such a feature without requiring any specific option, it might inadvertently lead users to expect that in-place file editing is possible by default. 

Since `mdtt` is primarily designed to seamlessly integrate with stdout and stdin, focusing on printing rather than editing files, I've decided not to include prompts about discarding unsaved changes. However, I might consider adding this feature if it seems useful or if there's some interest. 😊
